### ISSUE TITLE
Hiveos load problem

### ISSUE THREAD

**Issue by altinsoft** [bzminer/bzminer#19]
Hi,

We are solo mining Alephium on Hiveos. (with AMD graphics cards).
Load average is getting too high. What is the solution to this problem? Please provide a solution.

![resim](https://user-images.githubusercontent.com/31034706/150639026-eaf0c0f2-ccd8-4520-89c5-095477d50b93.png)

Load average is getting too high !

Thank you.

**Comment by bzminer** [comment]
hey @altinsoft , the next release should fix the load issue! i'll post back here when its out

**Comment by altinsoft** [comment]
@bzminer problem solved ?

**Comment by altinsoft** [comment]
![resim](https://user-images.githubusercontent.com/31034706/151512279-1d2795bb-19fc-477f-8980-dd589543d386.png)

The problem persists on Hiveos. @bzminer
