### ISSUE TITLE
Duplicate zil shares

### ISSUE THREAD

**Issue by 53nsk** [bzminer/bzminer#198]
Versions 14.0.0b8, 14.0.0 and 14.0.1 are producing duplicate zil shares (marked as invalids on crazypool) while 13.4.0 is working fine. The message is: <Warn> GPU 7:0: zil solution rejected: code: 22, message: Duplicate share (85ms).

**Comment by bzminer** [comment]
Hey @53nsk , just pushed a beta, 14.0.2b1 that should fix this issue, will push a hotfox later today

**Comment by 53nsk** [comment]
@bzminer looks like it is not fixed, observing same behaviour in 14.0.2, getting many rejects: "<Warn> GPU 9:0: zil solution rejected: code: 22, message: Duplicate share (77ms)".

**Comment by 53nsk** [comment]
Fixed in 14.1.0b1.
